### ISSUE TITLE
Auto assign

### ISSUE THREAD

**Issue by hbaileylxd** [cgkineo/adapt-nudge#2]
It won't let me save my settings without setting Auto_assign to true, so is there a point in having the option true/false?

I'm not sure I understand the phrasing so not quite sure what it does!

**Comment by chris-steele** [comment]
Sorry @hmaffin I didn't get any notification about this issue from GitHub. Are you still having an issue? If so can you explain some more about what is happening?

**Comment by hbaileylxd** [comment]
Yes - in the Authoring Tool project settings, it won't allow you to save the settings if Auto_Assign if you have left it as False.

![image](https://cloud.githubusercontent.com/assets/11558341/24002144/e310742a-0a57-11e7-87a2-4faba5b22a59.png)

![image](https://cloud.githubusercontent.com/assets/11558341/24002154/e9ed24be-0a57-11e7-9125-edc6e9e1880c.png)

I know some people are having issues with labels and so on too - in the gitter chat - https://gitter.im/adaptlearning/adapt_authoring

**Comment by chris-steele** [comment]
@hmaffin I'm wondering if this is something to do with the schema. I'm wondering if @taylortom can help? Is it wrong to set a boolean property to required (and validate it)?

**Comment by taylortom** [comment]
Yep, looks as though it shouldn't be required. AFAIK, it's only really useful in cases where you can't specify a default value.

**Comment by chris-steele** [comment]
@hmaffin this should now be fixed
