### ISSUE TITLE
Can't seem to find how to set the labels using Authoring Tool

### ISSUE THREAD

**Issue by hbaileylxd** [cgkineo/adapt-nudge#4]
Are we missing something?!

**Comment by chris-steele** [comment]
@hmaffin these are set in `course.json` on the `_globals` object. Have a look at https://github.com/chris-steele/adapt-nudge#configuration-of-labels

**Comment by chris-steele** [comment]
@hmaffin did you manage to do this ok?

**Comment by hbaileylxd** [comment]
Ahhh I see it now yes, thanks Chris!
