### ISSUE TITLE
PLP Feedback

### ISSUE THREAD

**Issue by mldaq** [cgkineo/adapt-nudge#5]
The plp feedback only seems to show up after I leave a page and come back. I would expect that if I skip an activity and get to the end of the page the plp feedback would trigger letting me know that I am not complete. It is showing up if I leave the page and come back. Many users would believe they are done and once completed all pages would leave the course only to find out they received an incomplete for the course. This is an issue we are having which is part of the reason why we would like to use an extension like this. Can we fix this?

**Comment by moloko** [comment]
@mldaq sounds to me more like you need [pageIncompletePrompt](https://github.com/cgkineo/adapt-pageIncompletePrompt) ?

**Comment by chris-steele** [comment]
Agreed it does seem like https://github.com/cgkineo/adapt-pageIncompletePrompt would be useful here. Closing this issue. Please find us in the forums if you would like to discuss further.
